name: Learning Github actions - Node
on: [push]
jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install express
      - run: npm install @hapi/hapi
      - run: npm --version
      - run: node --version
      - name: working-with-vars
        env: 
            NAMED: Arsalan
        run: node -p 'console.log("hello"); process.env.NAMED'
      
  
